### PR TITLE
Adds simple support for POST and PUT

### PR DESCRIPTION
**Pull request by software-atelier**
Here we go again :)

### CODE REVIEW

**Comment by codemee** [comment]
I'll chekc for this tomarrow.Thanks.

**Comment by software-atelier** [comment]
Please wait with merging. There is still an issue. I'll come back to you.

**Comment by software-atelier** [comment]
I fixed it. I missunderstood some python specifics. Since micropython does not support method inspection and I wanted to make sure your WebServer stays compatible, I had to introduce HTTP Method specific registration methods.

- `onGetPath` (same as `onPath`)
- `onPostPath`
- `onPutPath`

**Comment by codemee** [comment]
I've merged this commit, very thanks.

**Pull request merged**
